- name: install Nginx
  hosts: all
  tasks: 
    - name: install Nginx on Debian
      apt:
          name: nginx
          state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    -  name: install Nginx on Redhat
       yum:
          name: nginx
          state: present
       when: ansible_os_family == "RedHat" or ansible_os_family == "SUSE"