#!/bin/bash
# updating the ami
sudo yum update -y
# adding jenkins repo
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
# importing key 
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade -y
# installing java 
sudo amazon-linux-extras install java-openjdk11 -y
# Install Jenkins:
sudo yum install jenkins -y
# starting and enabling jenkins 
sudo systemctl start jenkins && sudo systemctl enable jenkins 




# to install ansible in the machine 
sudo amazon-linux-extras install ansible2 -y