global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
    - job_name: 'node'
      scrape_interval: 15s
      scrape_timeout: 5s
      sample_limit: 1000
      static_configs:
        - targets: ['172.16.12.1:9090']

    - job_name: 'nodes'
      scrape_interval: 30s
      scrape_timeout: 30s
      scheme: https # default value -> http
      metrics_path: /stats/metrics #default value -> /metric
      static_configs:
        - targets: ['10.231.1.2.:9090', '192.168.43.9090'] # here we have 2 targets that we wanted to scrape
        
    - job_name: 'jenkins'
      static_configs:
        - targets: ['localhost:8080']

#configuration related to AlertManager
alerting:


#Rule files specifies a list of files rules are read from

rule_files:

#Settings related to the remote read/write feature.
remote_read:
remote_write:

#Storage related settings 
storage: